version: "3"
services: 
    yazlab3-go-system:
        container_name: yazlab3-go-system
        image: yazlab3-go-system
        restart: always
        build: .
        ports: 
            - "8080:8080"
    
    mysql:
        image: mongo
        ports: 
            - "27017:27017"
        environment: 
            MONGODB_URI : "mongodb://mongo/"
            #MYSQL_ROOT_PASSWORD : "123456"
            # MYSQL_USER : "root"
            # MYSQL_RANDOM_ROOT_PASSWORD : "yes"
            # MYSQL_PASSWORD : "root"
            # MYSQL_DATABASE : "db_my_go_app"
            # MYSQL_PORT : "3306"
            # MYSQL_HOST : "db"
        container_name: mysql-docker